server:
  port: 8080
spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.110.200
    port: 5672
    username: why
    password: 123456
    virtual-host: /vhost
    #确认消息已发送到交换机(Exchange)(确认模式)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)(回退模式)
    publisher-returns: true
