spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_db?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    #type: com.alibaba.druid.pool.DruidDataSource

    druid:
      aop-patterns: com.example.*  #监控SpringBean
      filters: stat,wall,slf4j     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
       #连接池的设置
      max-active: 20    #最大连接池数量 maxIdle已经不再使用
      initial-size: 5  #初始化时建立物理连接的个数
      min-idle: 5      #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000  #既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 30000    #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      validation-query: select 'x'              #用来检测连接是否有效的sql 必须是一个查询语句
      test-on-borrow: false                     #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false                     #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-while-idle: true  #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      pool-prepared-statements: true       #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20  #当值大于0时poolPreparedStatements会自动修改为true
      #exception-sorter: true               #当数据库抛出不可恢复的异常时,抛弃该连接




mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:Mapper/*.xml