spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 190918
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: warn  #//由低到高   trace<debug<info<warn<error
    com.example.demo1.mapper: debug
